version: '3.8'

services: 

  alta-store-app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - 8080:8080
    # working_dir: /alta-store
    # volumes: 
    #   - ./:/alta-store
    # environment: 
    #   MYSQL_HOST: mysql
    #   MYSQL_USER: root
    #   MYSQL_PASSWORD: 123ABC4d.
    #   MYSQL_DB: alta-store
    restart: on-failure
    depends_on:
      - mysql
    networks: 
      - alta

  mysql:
    image: mysql
    environment: 
      MYSQL_ROOT_PASSWORD: 123ABC4d.
      MYSQL_DATABASE: alta-store
    ports: 
      - 3308:3306
    volumes: 
      - alta-store-mysql-data:/var/lib/mysql
    networks: 
      - alta

volumes: 
  alta-store-mysql-data:

networks: 
  alta:
    driver: bridge

  # alta-store-app:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile
  #   ports: 
  #     - "8080:8080"
  #   depends_on:
  #     - mysql-development

# version: "3.8"

# services: 
#   app:
#     container_name: full_app
#     build: .
#     ports: 
#       - 8080:8080
#     restart: on-failure
#     # working_dir: /app
#     volumes: 
#       # - ./:/app
#       - api:/usr/src/app/
#     # environment: 
#     #   MYSQL_HOST: localhost
#     #   MYSQL_USER: root
#     #   MYSQL_PASSWORD: 123ABCd4.
#     #   MYSQL_DB: alta-store
#     depends_on: 
#       - database-mysql
#     networks: 
#       - alta

#   database-mysql:
#     image: mysql:latest
#     container_name: full_db_mysql
#     ports: 
#       - 3306:3306
#     environment: 
#       MYSQL_ROOT_HOST: 127.0.0.1
#       MYSQL_USER: root
#       MYSQL_PASSWORD: 123ABC4d.
#       MYSQL_DATABASE: alta-store
#       MYSQL_ROOT_PASSWORD: 123ABC4d.
#     volumes: 
#       - alta-mysql-data:/var/lib/mysql
#     networks: 
#       - alta

# volumes: 
#   api:
#   alta-mysql-data:

# # Networks to be created to facilitate communication between containers
# networks:
#   alta:
#     driver: bridge

# version: "3.8"

# services:
#   alta_store:
#     build: 
#       context: .
#       dockerfile: Dockerfile
#     ports: 
#       - 8080:8080
#     depends_on: 
#       mysql_server:
#         condition: service_healthy

#   mysql_server:
#     image: mysql:latest
#     environment: 
#       MYSQL_ROOT_PASSWORD: 123ABCd4.
#     ports: 
#       - 3306:3306
#     restart: always
#     volumes: 
#       - alta-mysql-data:/var/lib/mysql
#     healthcheck:
#       test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
#       timeout: 20s
#       retries: 10

# volumes: 
#   alta-mysql-data: