version: "3.8"

services:
  alta-store:
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - 8080:8080
    depends_on: 
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:latest
    environment: 
      MYSQL_ROOT_PASSWORD: 123ABCd4.
    ports: 
      - 3306:3306
    restart: always
    volumes: 
      - alta-mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes: 
  alta-mysql-data: